# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Tileset.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Sprite_pb2 as Sprite__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Tileset.proto',
  package='Lux.Protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rTileset.proto\x12\x0cLux.Protobuf\x1a\x0cSprite.proto\"\x8f\x01\n\x07Tileset\x12I\n\x12tileIdToSpriteName\x18\x01 \x03(\x0b\x32-.Lux.Protobuf.Tileset.TileIdToSpriteNameEntry\x1a\x39\n\x17TileIdToSpriteNameEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[Sprite__pb2.DESCRIPTOR,])




_TILESET_TILEIDTOSPRITENAMEENTRY = _descriptor.Descriptor(
  name='TileIdToSpriteNameEntry',
  full_name='Lux.Protobuf.Tileset.TileIdToSpriteNameEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Lux.Protobuf.Tileset.TileIdToSpriteNameEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Lux.Protobuf.Tileset.TileIdToSpriteNameEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=189,
)

_TILESET = _descriptor.Descriptor(
  name='Tileset',
  full_name='Lux.Protobuf.Tileset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tileIdToSpriteName', full_name='Lux.Protobuf.Tileset.tileIdToSpriteName', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TILESET_TILEIDTOSPRITENAMEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=189,
)

_TILESET_TILEIDTOSPRITENAMEENTRY.containing_type = _TILESET
_TILESET.fields_by_name['tileIdToSpriteName'].message_type = _TILESET_TILEIDTOSPRITENAMEENTRY
DESCRIPTOR.message_types_by_name['Tileset'] = _TILESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tileset = _reflection.GeneratedProtocolMessageType('Tileset', (_message.Message,), {

  'TileIdToSpriteNameEntry' : _reflection.GeneratedProtocolMessageType('TileIdToSpriteNameEntry', (_message.Message,), {
    'DESCRIPTOR' : _TILESET_TILEIDTOSPRITENAMEENTRY,
    '__module__' : 'Tileset_pb2'
    # @@protoc_insertion_point(class_scope:Lux.Protobuf.Tileset.TileIdToSpriteNameEntry)
    })
  ,
  'DESCRIPTOR' : _TILESET,
  '__module__' : 'Tileset_pb2'
  # @@protoc_insertion_point(class_scope:Lux.Protobuf.Tileset)
  })
_sym_db.RegisterMessage(Tileset)
_sym_db.RegisterMessage(Tileset.TileIdToSpriteNameEntry)


_TILESET_TILEIDTOSPRITENAMEENTRY._options = None
# @@protoc_insertion_point(module_scope)
