// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Tileset.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lux.Protobuf {

  /// <summary>Holder for reflection information generated from Tileset.proto</summary>
  public static partial class TilesetReflection {

    #region Descriptor
    /// <summary>File descriptor for Tileset.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TilesetReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1UaWxlc2V0LnByb3RvEgxMdXguUHJvdG9idWYaDFNwcml0ZS5wcm90byKP",
            "AQoHVGlsZXNldBJJChJ0aWxlSWRUb1Nwcml0ZU5hbWUYASADKAsyLS5MdXgu",
            "UHJvdG9idWYuVGlsZXNldC5UaWxlSWRUb1Nwcml0ZU5hbWVFbnRyeRo5ChdU",
            "aWxlSWRUb1Nwcml0ZU5hbWVFbnRyeRILCgNrZXkYASABKAUSDQoFdmFsdWUY",
            "AiABKAk6AjgBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Lux.Protobuf.SpriteReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Lux.Protobuf.Tileset), global::Lux.Protobuf.Tileset.Parser, new[]{ "TileIdToSpriteName" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Tileset : pb::IMessage<Tileset> {
    private static readonly pb::MessageParser<Tileset> _parser = new pb::MessageParser<Tileset>(() => new Tileset());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Tileset> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lux.Protobuf.TilesetReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Tileset() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Tileset(Tileset other) : this() {
      tileIdToSpriteName_ = other.tileIdToSpriteName_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Tileset Clone() {
      return new Tileset(this);
    }

    /// <summary>Field number for the "tileIdToSpriteName" field.</summary>
    public const int TileIdToSpriteNameFieldNumber = 1;
    private static readonly pbc::MapField<int, string>.Codec _map_tileIdToSpriteName_codec
        = new pbc::MapField<int, string>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForString(18, ""), 10);
    private readonly pbc::MapField<int, string> tileIdToSpriteName_ = new pbc::MapField<int, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, string> TileIdToSpriteName {
      get { return tileIdToSpriteName_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Tileset);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Tileset other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!TileIdToSpriteName.Equals(other.TileIdToSpriteName)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= TileIdToSpriteName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      tileIdToSpriteName_.WriteTo(output, _map_tileIdToSpriteName_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += tileIdToSpriteName_.CalculateSize(_map_tileIdToSpriteName_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Tileset other) {
      if (other == null) {
        return;
      }
      tileIdToSpriteName_.Add(other.tileIdToSpriteName_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            tileIdToSpriteName_.AddEntriesFrom(input, _map_tileIdToSpriteName_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
